In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

In [3]:
hello  = tf.constant("Hello")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [6]:
print(hello)

tf.Tensor(b'Hello', shape=(), dtype=string)


In [15]:
tf.compat.v1.disable_eager_execution()#here we created session
hello  = tf.constant("Hello")
world = tf.constant("World")
sess = tf.compat.v1.Session()
print(sess.run(hello+world))

b'HelloWorld'


In [20]:
import tensorflow as tf
msg = tf.constant('Hello, TensorFlow!')
tf.print(msg)

Hello, TensorFlow!


In [21]:
import tensorflow as tf

tf.compat.v1.disable_eager_execution()

hello = tf.constant('Hello, TensorFlow!')

sess = tf.compat.v1.Session()

print(sess.run(hello))

b'Hello, TensorFlow!'


In [22]:
var1=tf.constant(10)
var2=tf.constant(10)

In [23]:
tf.compat.v1.disable_eager_execution()

In [24]:
sess = tf.compat.v1.Session()

In [25]:
print(sess.run(var1*var2))

100


In [26]:
#making matrix in tenserflow
const = tf.constant(10)

In [27]:
mat_1=tf.fill((5,5),10)#dimension is 5,5 and every digit 10

In [28]:
zeros=tf.zeros((5,5))
ones = tf.ones((5,5))

In [29]:
randn = tf.random.normal((4,4),mean=0,stddev=1.0)

In [30]:
myops = [const,mat_1,zeros,ones,randn,randu]

In [31]:
import tensorflow.compat.v1 as tfc
sess = tfc.InteractiveSession()

In [32]:
for op in myops:
    #print(sess.run(op))
    print(op.eval())
    print("\n")

10


[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[ 0.31546897  1.0611076   1.6782709   3.2529957 ]
 [-0.84843826 -0.41154248 -0.2904664  -1.2268364 ]
 [-1.3872367  -1.5899125   0.20876731  0.2481517 ]
 [ 2.0350533   0.90123266  1.2970005  -0.650924  ]]




In [33]:
a = tf.constant([[1,2],[3,4]])

In [34]:
a.get_shape()

TensorShape([2, 2])

In [35]:
b = tf.constant([[10],[100]])

In [36]:
b.get_shape()

TensorShape([2, 1])

In [37]:
result = tf.matmul(a,b)

In [38]:
sess.run(result)

array([[210],
       [430]])